/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.leonardo.ltl.lTL.Input#getInputs <em>Inputs</em>}</li>
 * </ul>
 *
 * @see org.leonardo.ltl.lTL.LTLPackage#getInput()
 * @model
 * @generated
 */
public interface Input extends EObject
{
  /**
   * Returns the value of the '<em><b>Inputs</b></em>' reference list.
   * The list contents are of type {@link org.leonardo.ltl.lTL.TestableEntity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inputs</em>' reference list.
   * @see org.leonardo.ltl.lTL.LTLPackage#getInput_Inputs()
   * @model
   * @generated
   */
  EList<TestableEntity> getInputs();

} // Input
