/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.leonardo.ltl.lTL.LTLPackage
 * @generated
 */
public interface LTLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LTLFactory eINSTANCE = org.leonardo.ltl.lTL.impl.LTLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package</em>'.
   * @generated
   */
  Package createPackage();

  /**
   * Returns a new object of class '<em>Testing</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing</em>'.
   * @generated
   */
  Testing createTesting();

  /**
   * Returns a new object of class '<em>Testing Activity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing Activity</em>'.
   * @generated
   */
  TestingActivity createTestingActivity();

  /**
   * Returns a new object of class '<em>Testing Design</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing Design</em>'.
   * @generated
   */
  TestingDesign createTestingDesign();

  /**
   * Returns a new object of class '<em>Testing Realisation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing Realisation</em>'.
   * @generated
   */
  TestingRealisation createTestingRealisation();

  /**
   * Returns a new object of class '<em>Testing Analysis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing Analysis</em>'.
   * @generated
   */
  TestingAnalysis createTestingAnalysis();

  /**
   * Returns a new object of class '<em>Testable Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testable Entity</em>'.
   * @generated
   */
  TestableEntity createTestableEntity();

  /**
   * Returns a new object of class '<em>Test Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test Requirement</em>'.
   * @generated
   */
  TestRequirement createTestRequirement();

  /**
   * Returns a new object of class '<em>Test Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test Specification</em>'.
   * @generated
   */
  TestSpecification createTestSpecification();

  /**
   * Returns a new object of class '<em>Test Suite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test Suite</em>'.
   * @generated
   */
  TestSuite createTestSuite();

  /**
   * Returns a new object of class '<em>Test Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test Case</em>'.
   * @generated
   */
  TestCase createTestCase();

  /**
   * Returns a new object of class '<em>Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input</em>'.
   * @generated
   */
  Input createInput();

  /**
   * Returns a new object of class '<em>Expected Results</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expected Results</em>'.
   * @generated
   */
  ExpectedResults createExpectedResults();

  /**
   * Returns a new object of class '<em>Testing Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Testing Method</em>'.
   * @generated
   */
  TestingMethod createTestingMethod();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LTLPackage getLTLPackage();

} //LTLFactory
