/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.leonardo.ltl.lTL.LTLFactory
 * @model kind="package"
 * @generated
 */
public interface LTLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lTL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.leonardo.org/ltl/LTL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lTL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LTLPackage eINSTANCE = org.leonardo.ltl.lTL.impl.LTLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.ModelImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Package</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PACKAGE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.PackageImpl <em>Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.PackageImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getPackage()
   * @generated
   */
  int PACKAGE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Testings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__TESTINGS = 2;

  /**
   * The feature id for the '<em><b>Testable Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__TESTABLE_ENTITIES = 3;

  /**
   * The feature id for the '<em><b>Test Requirements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__TEST_REQUIREMENTS = 4;

  /**
   * The feature id for the '<em><b>Test Specifications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__TEST_SPECIFICATIONS = 5;

  /**
   * The feature id for the '<em><b>Testing Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__TESTING_METHODS = 6;

  /**
   * The number of structural features of the '<em>Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestingImpl <em>Testing</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestingImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTesting()
   * @generated
   */
  int TESTING = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Activities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING__ACTIVITIES = 2;

  /**
   * The feature id for the '<em><b>Requirements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING__REQUIREMENTS = 3;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING__ENTITIES = 4;

  /**
   * The number of structural features of the '<em>Testing</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestingActivityImpl <em>Testing Activity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestingActivityImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingActivity()
   * @generated
   */
  int TESTING_ACTIVITY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ACTIVITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ACTIVITY__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ACTIVITY__METHOD = 2;

  /**
   * The number of structural features of the '<em>Testing Activity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ACTIVITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestingDesignImpl <em>Testing Design</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestingDesignImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingDesign()
   * @generated
   */
  int TESTING_DESIGN = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_DESIGN__NAME = TESTING_ACTIVITY__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_DESIGN__DESCRIPTION = TESTING_ACTIVITY__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_DESIGN__METHOD = TESTING_ACTIVITY__METHOD;

  /**
   * The number of structural features of the '<em>Testing Design</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_DESIGN_FEATURE_COUNT = TESTING_ACTIVITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestingRealisationImpl <em>Testing Realisation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestingRealisationImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingRealisation()
   * @generated
   */
  int TESTING_REALISATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_REALISATION__NAME = TESTING_ACTIVITY__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_REALISATION__DESCRIPTION = TESTING_ACTIVITY__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_REALISATION__METHOD = TESTING_ACTIVITY__METHOD;

  /**
   * The number of structural features of the '<em>Testing Realisation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_REALISATION_FEATURE_COUNT = TESTING_ACTIVITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestingAnalysisImpl <em>Testing Analysis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestingAnalysisImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingAnalysis()
   * @generated
   */
  int TESTING_ANALYSIS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ANALYSIS__NAME = TESTING_ACTIVITY__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ANALYSIS__DESCRIPTION = TESTING_ACTIVITY__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ANALYSIS__METHOD = TESTING_ACTIVITY__METHOD;

  /**
   * The number of structural features of the '<em>Testing Analysis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_ANALYSIS_FEATURE_COUNT = TESTING_ACTIVITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestableEntityImpl <em>Testable Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestableEntityImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestableEntity()
   * @generated
   */
  int TESTABLE_ENTITY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTABLE_ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTABLE_ENTITY__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Testable Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTABLE_ENTITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestRequirementImpl <em>Test Requirement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestRequirementImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestRequirement()
   * @generated
   */
  int TEST_REQUIREMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_REQUIREMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_REQUIREMENT__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Test Requirement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_REQUIREMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestSpecificationImpl <em>Test Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestSpecificationImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestSpecification()
   * @generated
   */
  int TEST_SPECIFICATION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SPECIFICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SPECIFICATION__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Test Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SPECIFICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestSuiteImpl <em>Test Suite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestSuiteImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestSuite()
   * @generated
   */
  int TEST_SUITE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__NAME = TEST_SPECIFICATION__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__DESCRIPTION = TEST_SPECIFICATION__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Test Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__TEST_CASES = TEST_SPECIFICATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Test Suite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE_FEATURE_COUNT = TEST_SPECIFICATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestCaseImpl <em>Test Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestCaseImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestCase()
   * @generated
   */
  int TEST_CASE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__NAME = TEST_SPECIFICATION__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__DESCRIPTION = TEST_SPECIFICATION__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Precondition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__PRECONDITION = TEST_SPECIFICATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Postcondition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__POSTCONDITION = TEST_SPECIFICATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Inputs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__INPUTS = TEST_SPECIFICATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Expected Results</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__EXPECTED_RESULTS = TEST_SPECIFICATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Test Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE_FEATURE_COUNT = TEST_SPECIFICATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.InputImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getInput()
   * @generated
   */
  int INPUT = 12;

  /**
   * The feature id for the '<em><b>Inputs</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__INPUTS = 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.ExpectedResultsImpl <em>Expected Results</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.ExpectedResultsImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getExpectedResults()
   * @generated
   */
  int EXPECTED_RESULTS = 13;

  /**
   * The feature id for the '<em><b>Expects</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTED_RESULTS__EXPECTS = 0;

  /**
   * The number of structural features of the '<em>Expected Results</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTED_RESULTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.leonardo.ltl.lTL.impl.TestingMethodImpl <em>Testing Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.leonardo.ltl.lTL.impl.TestingMethodImpl
   * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingMethod()
   * @generated
   */
  int TESTING_METHOD = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_METHOD__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_METHOD__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Testing Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_METHOD_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.leonardo.ltl.lTL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Model#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Package</em>'.
   * @see org.leonardo.ltl.lTL.Model#getPackage()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Package();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.Package <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package</em>'.
   * @see org.leonardo.ltl.lTL.Package
   * @generated
   */
  EClass getPackage();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.Package#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.Package#getName()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.Package#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.Package#getDescription()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Package#getTestings <em>Testings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Testings</em>'.
   * @see org.leonardo.ltl.lTL.Package#getTestings()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_Testings();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Package#getTestableEntities <em>Testable Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Testable Entities</em>'.
   * @see org.leonardo.ltl.lTL.Package#getTestableEntities()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_TestableEntities();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Package#getTestRequirements <em>Test Requirements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Requirements</em>'.
   * @see org.leonardo.ltl.lTL.Package#getTestRequirements()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_TestRequirements();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Package#getTestSpecifications <em>Test Specifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Specifications</em>'.
   * @see org.leonardo.ltl.lTL.Package#getTestSpecifications()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_TestSpecifications();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Package#getTestingMethods <em>Testing Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Testing Methods</em>'.
   * @see org.leonardo.ltl.lTL.Package#getTestingMethods()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_TestingMethods();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.Testing <em>Testing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testing</em>'.
   * @see org.leonardo.ltl.lTL.Testing
   * @generated
   */
  EClass getTesting();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.Testing#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.Testing#getName()
   * @see #getTesting()
   * @generated
   */
  EAttribute getTesting_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.Testing#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.Testing#getDescription()
   * @see #getTesting()
   * @generated
   */
  EAttribute getTesting_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Testing#getActivities <em>Activities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Activities</em>'.
   * @see org.leonardo.ltl.lTL.Testing#getActivities()
   * @see #getTesting()
   * @generated
   */
  EReference getTesting_Activities();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Testing#getRequirements <em>Requirements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Requirements</em>'.
   * @see org.leonardo.ltl.lTL.Testing#getRequirements()
   * @see #getTesting()
   * @generated
   */
  EReference getTesting_Requirements();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.Testing#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.leonardo.ltl.lTL.Testing#getEntities()
   * @see #getTesting()
   * @generated
   */
  EReference getTesting_Entities();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestingActivity <em>Testing Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testing Activity</em>'.
   * @see org.leonardo.ltl.lTL.TestingActivity
   * @generated
   */
  EClass getTestingActivity();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestingActivity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.TestingActivity#getName()
   * @see #getTestingActivity()
   * @generated
   */
  EAttribute getTestingActivity_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestingActivity#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.TestingActivity#getDescription()
   * @see #getTestingActivity()
   * @generated
   */
  EAttribute getTestingActivity_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.TestingActivity#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Method</em>'.
   * @see org.leonardo.ltl.lTL.TestingActivity#getMethod()
   * @see #getTestingActivity()
   * @generated
   */
  EReference getTestingActivity_Method();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestingDesign <em>Testing Design</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testing Design</em>'.
   * @see org.leonardo.ltl.lTL.TestingDesign
   * @generated
   */
  EClass getTestingDesign();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestingRealisation <em>Testing Realisation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testing Realisation</em>'.
   * @see org.leonardo.ltl.lTL.TestingRealisation
   * @generated
   */
  EClass getTestingRealisation();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestingAnalysis <em>Testing Analysis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testing Analysis</em>'.
   * @see org.leonardo.ltl.lTL.TestingAnalysis
   * @generated
   */
  EClass getTestingAnalysis();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestableEntity <em>Testable Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testable Entity</em>'.
   * @see org.leonardo.ltl.lTL.TestableEntity
   * @generated
   */
  EClass getTestableEntity();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestableEntity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.TestableEntity#getName()
   * @see #getTestableEntity()
   * @generated
   */
  EAttribute getTestableEntity_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestableEntity#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.TestableEntity#getDescription()
   * @see #getTestableEntity()
   * @generated
   */
  EAttribute getTestableEntity_Description();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestRequirement <em>Test Requirement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Requirement</em>'.
   * @see org.leonardo.ltl.lTL.TestRequirement
   * @generated
   */
  EClass getTestRequirement();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestRequirement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.TestRequirement#getName()
   * @see #getTestRequirement()
   * @generated
   */
  EAttribute getTestRequirement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestRequirement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.TestRequirement#getDescription()
   * @see #getTestRequirement()
   * @generated
   */
  EAttribute getTestRequirement_Description();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestSpecification <em>Test Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Specification</em>'.
   * @see org.leonardo.ltl.lTL.TestSpecification
   * @generated
   */
  EClass getTestSpecification();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestSpecification#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.TestSpecification#getName()
   * @see #getTestSpecification()
   * @generated
   */
  EAttribute getTestSpecification_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestSpecification#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.TestSpecification#getDescription()
   * @see #getTestSpecification()
   * @generated
   */
  EAttribute getTestSpecification_Description();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestSuite <em>Test Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Suite</em>'.
   * @see org.leonardo.ltl.lTL.TestSuite
   * @generated
   */
  EClass getTestSuite();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.TestSuite#getTestCases <em>Test Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Cases</em>'.
   * @see org.leonardo.ltl.lTL.TestSuite#getTestCases()
   * @see #getTestSuite()
   * @generated
   */
  EReference getTestSuite_TestCases();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestCase <em>Test Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Case</em>'.
   * @see org.leonardo.ltl.lTL.TestCase
   * @generated
   */
  EClass getTestCase();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestCase#getPrecondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Precondition</em>'.
   * @see org.leonardo.ltl.lTL.TestCase#getPrecondition()
   * @see #getTestCase()
   * @generated
   */
  EAttribute getTestCase_Precondition();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestCase#getPostcondition <em>Postcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Postcondition</em>'.
   * @see org.leonardo.ltl.lTL.TestCase#getPostcondition()
   * @see #getTestCase()
   * @generated
   */
  EAttribute getTestCase_Postcondition();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.TestCase#getInputs <em>Inputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inputs</em>'.
   * @see org.leonardo.ltl.lTL.TestCase#getInputs()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_Inputs();

  /**
   * Returns the meta object for the containment reference list '{@link org.leonardo.ltl.lTL.TestCase#getExpectedResults <em>Expected Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expected Results</em>'.
   * @see org.leonardo.ltl.lTL.TestCase#getExpectedResults()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_ExpectedResults();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.leonardo.ltl.lTL.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the reference list '{@link org.leonardo.ltl.lTL.Input#getInputs <em>Inputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Inputs</em>'.
   * @see org.leonardo.ltl.lTL.Input#getInputs()
   * @see #getInput()
   * @generated
   */
  EReference getInput_Inputs();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.ExpectedResults <em>Expected Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expected Results</em>'.
   * @see org.leonardo.ltl.lTL.ExpectedResults
   * @generated
   */
  EClass getExpectedResults();

  /**
   * Returns the meta object for the attribute list '{@link org.leonardo.ltl.lTL.ExpectedResults#getExpects <em>Expects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Expects</em>'.
   * @see org.leonardo.ltl.lTL.ExpectedResults#getExpects()
   * @see #getExpectedResults()
   * @generated
   */
  EAttribute getExpectedResults_Expects();

  /**
   * Returns the meta object for class '{@link org.leonardo.ltl.lTL.TestingMethod <em>Testing Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Testing Method</em>'.
   * @see org.leonardo.ltl.lTL.TestingMethod
   * @generated
   */
  EClass getTestingMethod();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestingMethod#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.leonardo.ltl.lTL.TestingMethod#getName()
   * @see #getTestingMethod()
   * @generated
   */
  EAttribute getTestingMethod_Name();

  /**
   * Returns the meta object for the attribute '{@link org.leonardo.ltl.lTL.TestingMethod#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.leonardo.ltl.lTL.TestingMethod#getDescription()
   * @see #getTestingMethod()
   * @generated
   */
  EAttribute getTestingMethod_Description();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LTLFactory getLTLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.ModelImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PACKAGE = eINSTANCE.getModel_Package();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.PackageImpl <em>Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.PackageImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getPackage()
     * @generated
     */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__NAME = eINSTANCE.getPackage_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__DESCRIPTION = eINSTANCE.getPackage_Description();

    /**
     * The meta object literal for the '<em><b>Testings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__TESTINGS = eINSTANCE.getPackage_Testings();

    /**
     * The meta object literal for the '<em><b>Testable Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__TESTABLE_ENTITIES = eINSTANCE.getPackage_TestableEntities();

    /**
     * The meta object literal for the '<em><b>Test Requirements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__TEST_REQUIREMENTS = eINSTANCE.getPackage_TestRequirements();

    /**
     * The meta object literal for the '<em><b>Test Specifications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__TEST_SPECIFICATIONS = eINSTANCE.getPackage_TestSpecifications();

    /**
     * The meta object literal for the '<em><b>Testing Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__TESTING_METHODS = eINSTANCE.getPackage_TestingMethods();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestingImpl <em>Testing</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestingImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTesting()
     * @generated
     */
    EClass TESTING = eINSTANCE.getTesting();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING__NAME = eINSTANCE.getTesting_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING__DESCRIPTION = eINSTANCE.getTesting_Description();

    /**
     * The meta object literal for the '<em><b>Activities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TESTING__ACTIVITIES = eINSTANCE.getTesting_Activities();

    /**
     * The meta object literal for the '<em><b>Requirements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TESTING__REQUIREMENTS = eINSTANCE.getTesting_Requirements();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TESTING__ENTITIES = eINSTANCE.getTesting_Entities();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestingActivityImpl <em>Testing Activity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestingActivityImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingActivity()
     * @generated
     */
    EClass TESTING_ACTIVITY = eINSTANCE.getTestingActivity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING_ACTIVITY__NAME = eINSTANCE.getTestingActivity_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING_ACTIVITY__DESCRIPTION = eINSTANCE.getTestingActivity_Description();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TESTING_ACTIVITY__METHOD = eINSTANCE.getTestingActivity_Method();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestingDesignImpl <em>Testing Design</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestingDesignImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingDesign()
     * @generated
     */
    EClass TESTING_DESIGN = eINSTANCE.getTestingDesign();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestingRealisationImpl <em>Testing Realisation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestingRealisationImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingRealisation()
     * @generated
     */
    EClass TESTING_REALISATION = eINSTANCE.getTestingRealisation();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestingAnalysisImpl <em>Testing Analysis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestingAnalysisImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingAnalysis()
     * @generated
     */
    EClass TESTING_ANALYSIS = eINSTANCE.getTestingAnalysis();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestableEntityImpl <em>Testable Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestableEntityImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestableEntity()
     * @generated
     */
    EClass TESTABLE_ENTITY = eINSTANCE.getTestableEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTABLE_ENTITY__NAME = eINSTANCE.getTestableEntity_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTABLE_ENTITY__DESCRIPTION = eINSTANCE.getTestableEntity_Description();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestRequirementImpl <em>Test Requirement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestRequirementImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestRequirement()
     * @generated
     */
    EClass TEST_REQUIREMENT = eINSTANCE.getTestRequirement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_REQUIREMENT__NAME = eINSTANCE.getTestRequirement_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_REQUIREMENT__DESCRIPTION = eINSTANCE.getTestRequirement_Description();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestSpecificationImpl <em>Test Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestSpecificationImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestSpecification()
     * @generated
     */
    EClass TEST_SPECIFICATION = eINSTANCE.getTestSpecification();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_SPECIFICATION__NAME = eINSTANCE.getTestSpecification_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_SPECIFICATION__DESCRIPTION = eINSTANCE.getTestSpecification_Description();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestSuiteImpl <em>Test Suite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestSuiteImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestSuite()
     * @generated
     */
    EClass TEST_SUITE = eINSTANCE.getTestSuite();

    /**
     * The meta object literal for the '<em><b>Test Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_SUITE__TEST_CASES = eINSTANCE.getTestSuite_TestCases();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestCaseImpl <em>Test Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestCaseImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestCase()
     * @generated
     */
    EClass TEST_CASE = eINSTANCE.getTestCase();

    /**
     * The meta object literal for the '<em><b>Precondition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_CASE__PRECONDITION = eINSTANCE.getTestCase_Precondition();

    /**
     * The meta object literal for the '<em><b>Postcondition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_CASE__POSTCONDITION = eINSTANCE.getTestCase_Postcondition();

    /**
     * The meta object literal for the '<em><b>Inputs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__INPUTS = eINSTANCE.getTestCase_Inputs();

    /**
     * The meta object literal for the '<em><b>Expected Results</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__EXPECTED_RESULTS = eINSTANCE.getTestCase_ExpectedResults();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.InputImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Inputs</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT__INPUTS = eINSTANCE.getInput_Inputs();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.ExpectedResultsImpl <em>Expected Results</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.ExpectedResultsImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getExpectedResults()
     * @generated
     */
    EClass EXPECTED_RESULTS = eINSTANCE.getExpectedResults();

    /**
     * The meta object literal for the '<em><b>Expects</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPECTED_RESULTS__EXPECTS = eINSTANCE.getExpectedResults_Expects();

    /**
     * The meta object literal for the '{@link org.leonardo.ltl.lTL.impl.TestingMethodImpl <em>Testing Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.leonardo.ltl.lTL.impl.TestingMethodImpl
     * @see org.leonardo.ltl.lTL.impl.LTLPackageImpl#getTestingMethod()
     * @generated
     */
    EClass TESTING_METHOD = eINSTANCE.getTestingMethod();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING_METHOD__NAME = eINSTANCE.getTestingMethod_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING_METHOD__DESCRIPTION = eINSTANCE.getTestingMethod_Description();

  }

} //LTLPackage
