/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.leonardo.ltl.lTL.Model#getPackage <em>Package</em>}</li>
 * </ul>
 *
 * @see org.leonardo.ltl.lTL.LTLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Package</b></em>' containment reference list.
   * The list contents are of type {@link org.leonardo.ltl.lTL.Package}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' containment reference list.
   * @see org.leonardo.ltl.lTL.LTLPackage#getModel_Package()
   * @model containment="true"
   * @generated
   */
  EList<org.leonardo.ltl.lTL.Package> getPackage();

} // Model
