/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Testing Activity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.leonardo.ltl.lTL.TestingActivity#getName <em>Name</em>}</li>
 *   <li>{@link org.leonardo.ltl.lTL.TestingActivity#getDescription <em>Description</em>}</li>
 *   <li>{@link org.leonardo.ltl.lTL.TestingActivity#getMethod <em>Method</em>}</li>
 * </ul>
 *
 * @see org.leonardo.ltl.lTL.LTLPackage#getTestingActivity()
 * @model
 * @generated
 */
public interface TestingActivity extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.leonardo.ltl.lTL.LTLPackage#getTestingActivity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.leonardo.ltl.lTL.TestingActivity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.leonardo.ltl.lTL.LTLPackage#getTestingActivity_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.leonardo.ltl.lTL.TestingActivity#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' containment reference list.
   * The list contents are of type {@link org.leonardo.ltl.lTL.TestingMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' containment reference list.
   * @see org.leonardo.ltl.lTL.LTLPackage#getTestingActivity_Method()
   * @model containment="true"
   * @generated
   */
  EList<TestingMethod> getMethod();

} // TestingActivity
