/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Testing Realisation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.leonardo.ltl.lTL.LTLPackage#getTestingRealisation()
 * @model
 * @generated
 */
public interface TestingRealisation extends TestingActivity
{
} // TestingRealisation
