/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Suite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.leonardo.ltl.lTL.TestSuite#getTestCases <em>Test Cases</em>}</li>
 * </ul>
 *
 * @see org.leonardo.ltl.lTL.LTLPackage#getTestSuite()
 * @model
 * @generated
 */
public interface TestSuite extends TestSpecification
{
  /**
   * Returns the value of the '<em><b>Test Cases</b></em>' containment reference list.
   * The list contents are of type {@link org.leonardo.ltl.lTL.TestCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Cases</em>' containment reference list.
   * @see org.leonardo.ltl.lTL.LTLPackage#getTestSuite_TestCases()
   * @model containment="true"
   * @generated
   */
  EList<TestCase> getTestCases();

} // TestSuite
