/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.ltl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class LTLWebModule extends AbstractLTLWebModule {
}
