/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.ltl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LTLStandaloneSetup extends LTLStandaloneSetupGenerated {

	public static void doSetup() {
		new LTLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
