/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.ltl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link LTLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractLTLWebModule extends DefaultWebModule {

}
