/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.ltl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LTLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/leonardo/ltl/parser/antlr/internal/InternalLTL.tokens");
	}
}
