/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL.impl;

import org.eclipse.emf.ecore.EClass;

import org.leonardo.ltl.lTL.LTLPackage;
import org.leonardo.ltl.lTL.TestingRealisation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Testing Realisation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TestingRealisationImpl extends TestingActivityImpl implements TestingRealisation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TestingRealisationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LTLPackage.Literals.TESTING_REALISATION;
  }

} //TestingRealisationImpl
