/**
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl.lTL.impl;

import org.eclipse.emf.ecore.EClass;

import org.leonardo.ltl.lTL.LTLPackage;
import org.leonardo.ltl.lTL.TestingDesign;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Testing Design</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TestingDesignImpl extends TestingActivityImpl implements TestingDesign
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TestingDesignImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LTLPackage.Literals.TESTING_DESIGN;
  }

} //TestingDesignImpl
