/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.ltl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LTLUiModule extends AbstractLTLUiModule {

	public LTLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
