/*
 * generated by Xtext 2.31.0
 */
package org.leonardo.ltl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LTLRuntimeModule extends AbstractLTLRuntimeModule {
}
