/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.ltl.ui.tests;

import com.google.inject.Injector;
import com.leonardo.ltl.ui.internal.LtlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LTLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LtlActivator.getInstance().getInjector("com.leonardo.ltl.LTL");
	}

}
